// action types
const API_CALL_SEARCH_REQUEST = "API_CALL_SEARCH_REQUEST";
const API_CALL_SEARCH_SUCCESS = "API_CALL_SEARCH_SUCCESS";
const API_CALL_SEARCH_FAILURE = "API_CALL_SEARCH_FAILURE";

export default {
  types: {
    API_CALL_SEARCH_FAILURE,
    API_CALL_SEARCH_SUCCESS,
    API_CALL_SEARCH_REQUEST
  }
};
