export const GET_TRENDING_REQUEST = 'GET_TRENDING_REQUEST';
export const GET_TRENDING_COMPLETE = 'GET_TRENDING_COMPLETE';
export const GET_TRENDING_ERROR = 'GET_TRENDING_ERROR';

export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_COMPLETE = 'GET_SEARCH_COMPLETE';
export const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR';

export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_COMPLETE = 'GET_FAVORITES_COMPLETE';
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR';

export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_COMPLETE = 'GET_DETAILS_COMPLETE';
export const GET_DETAILS_ERROR = 'GET_DETAILS_ERROR';

export default {
  GET_TRENDING_REQUEST,
  GET_TRENDING_COMPLETE,
  GET_TRENDING_ERROR,
  GET_FAVORITES_REQUEST,
  GET_FAVORITES_COMPLETE,
  GET_FAVORITES_ERROR,
  GET_SEARCH_REQUEST,
  GET_SEARCH_COMPLETE,
  GET_SEARCH_ERROR
}