// Home
export const BEGIN_GET_GIFS_TRENDING_GIFS = 'BEGIN_GET_GIFS_TRENDING_GIFS';
export const SUCCESS_GET_GIFS_TRENDING_GIFS = 'SUCCESS_GET_GIFS_TRENDING_GIFS';
export const ERROR_GET_GIFS_TRENDING_GIFS = 'ERROR_GET_GIFS_TRENDING_GIFS';
export const SET_SEARCH_GIF_API = 'SET_SEARCH_GIF_API';
export const BEGIN_SEARCH_GIF_API = 'BEGIN_SEARCH_GIF_API';
export const SUCCESS_SEARCH_GIF_API = 'SUCCESS_SEARCH_GIF_API';
export const ERROR_SEARCH_GIF_API = 'ERROR_SEARCH_GIF_API';
export const HANDLE_FAVORITE_CHANGE = 'HANDLE_FAVORITE_CHANGE';
export const SET_NEW_STATUS_FAVORITES = 'SET_NEW_STATUS_FAVORITES';
