export default {
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_START: 'FETCH_START',
  FETCH_ERROR: 'FETCH_ERROR',
  FETCH_DATA: 'FETCH_DATA',
  FETCH_END: 'FETCH_END',
  LOCALSTORAGE_GET: 'LOCALSTORAGE_GET',
  LOCALSTORAGE_DATA: 'LOCALSTORAGE_DATA',
  LOCALSTORAGE_MODIFY: 'LOCALSTORAGE_MODIFY',
  LOCALSTORAGE_END: 'LOCALSTORAGE_END',
  LOCALSTORAGE_FIND: 'LOCALSTORAGE_FIND',
}