export default {
  FETCH_START: 'FETCH_START',
  FETCH_DATA: 'FETCH_DATA',
  FETCH_END: 'FETCH_END',
  LOCALSTORAGE_GET: 'LOCALSTORAGE_GET',
  LOCALSTORAGE_DATA: 'LOCALSTORAGE_DATA',
  LOCALSTORAGE_SET: 'LOCALSTORAGE_SET',
}